server: 
  profiles: 
    active: 
    - dev
---
spring:
  profiles: dev         #开发环境
  application: 
    name: microservicecloud-config-front-dev
---
spring:
  profiles: test         #测试环境
  application: 
    name: microservicecloud-config-front-test